platform :ios, '11.0'

use_frameworks!

target 'IORequestable_Example' do
  pod 'IORequestable', :path => '../'
  pod 'IORequestable/RxSwift', :path => '../'
end


# Post Install
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
    end
  end
end
