use_frameworks!

target 'IORequestable_Example' do
  pod 'IORequestable', :path => '../'

  target 'IORequestable_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
