use_frameworks!

target 'IORequestable_Example' do
  pod 'IORequestable', :path => '../'
  pod 'IORequestable/RxSwift', :path => '../'

  target 'IORequestable_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
  end
end
